version: "3.2"
services:
  keycloak:
    image: jboss/keycloak:3.1.0.Final
    ports: 
      - 8081:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
    networks:
      - webnet
networks: 
  webnet: